// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	about "gomall/app/frontend/biz/router/about"
	auth "gomall/app/frontend/biz/router/auth"
	home "gomall/app/frontend/biz/router/home"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	about.Register(r)

	auth.Register(r)

	home.Register(r)
}
